Fix invalid check for ID::hdlname attribute in a Cell
The current firrtl backend checks for the presence of the `hdlname` attribute in a `Cell` that represents a module instantiation. The backend uses this attribute to determine the name of the module that is to be instantiated.

    if (cell->type.begins_with("$paramod"))
    {
      log_assert(cell->has_attribute(ID::hdlname));
      instanceOf = cell->get_string_attribute(ID::hdlname);
    }

However, Yosys does not store such an attribute in a `Cell`, but rather in a `Module`. The code has an invalid assertion that requires this property (which cannot exist where it is queried) and the backend therefore crashes if run on a parameterized module (not a parameterized blackbox module).

For example, running the following verilog circuit with a parameterized input register chain connected to a simple passthrough module causes an assertion to fail.

    module top
    (
      input          clk,
      input  [63:0]  in_top,
      output [63:0]  out_top
    );

      wire [63:0] pass_in_wire;

      parametric_regchain #(2, 64) input_regchain(clk, in_top, pass_in_wire);

      nonparametric_passthrough passthrough
      (
        .pass_in(pass_in_wire),
        .pass_out(out_top),
      );

    endmodule

    module nonparametric_passthrough
    (
      input	 [63:0]	pass_in,
      output [63:0]	pass_out,
    );

      assign pass_out = pass_in;

    endmodule

    module parametric_regchain
    #(
      parameter NUM_STG = 8,
      parameter WIDTH = 32
    )
    (
      input              clk,
      input  [WIDTH-1:0] in,
      output [WIDTH-1:0] out
    );

      reg     [WIDTH-1:0] tmp[0:NUM_STG];
      integer             i;

      always @(*)
        tmp[0] = in;

      always @(posedge clk)
        for (i = 0; i < NUM_STG; i = i + 1)
          tmp[i+1] <= tmp[i];

      assign out = tmp[NUM_STG];

    endmodule

Input yosys script:

    read_verilog example.v
    hierarchy -check -top top
    proc
    opt_clean -purge
    write_firrtl example.fir

Yosys output:

    5.1. Executing PMUXTREE pass.
    ERROR: Assert `cell->has_attribute(ID::hdlname)' failed in backends/firrtl/firrtl.cc:698.

This PR fixes the following issues:
- Remove erroneous check for the `hdlname` attribute and fetch the instantiated `Module`'s name from the `Module`'s definition.

- Remove some code duplication by regrouping handling of parametric and non-parametric modules in a single place.

- Remove emission of an inline comment in a cell declaration. There is a branch in the code where instances can be declared as follows:

      inst x /* some comment */ of module_x

  However, firrtl does not support such /* ... */ comments and this looks like a previous verilog-like interpretation of what firrtl comments look like.

The generated output for the example above is a bit large due to the wiring generated by the backend, but I'll add it here to show that the pass produces valid firrtl:

    circuit top:
      module _paramod_parametric_regchain_NUM_STG_2_WIDTH_64:
        input clk: UInt<1>
        input in: UInt<64>
        output out: UInt<64>

        wire _auto_firrtl_cc_99_rename_invalid_rhs_references_18: UInt<64>
        wire tmp_1_: UInt<64>
        reg _procdff_16: UInt<64>, asClock(clk)
        reg _procdff_17: UInt<64>, asClock(clk)
        wire _0: UInt<64>

        _procdff_16 <= in
        _procdff_17 <= tmp_1_
        _0 <= _auto_firrtl_cc_99_rename_invalid_rhs_references_18

        _auto_firrtl_cc_99_rename_invalid_rhs_references_18 <= bits(_procdff_17, 63, 0)
        out <= bits(_0, 63, 0)
        tmp_1_ <= bits(_procdff_16, 63, 0)

      module nonparametric_passthrough:
        input pass_in: UInt<64>
        output pass_out: UInt<64>

        wire _auto_firrtl_cc_99_rename_invalid_rhs_references_19: UInt<64>
        wire _1: UInt<64>
        wire _2: UInt<64>

        _1 <= pass_in
        _2 <= _auto_firrtl_cc_99_rename_invalid_rhs_references_19

        _auto_firrtl_cc_99_rename_invalid_rhs_references_19 <= bits(_1, 63, 0)
        pass_out <= bits(_2, 63, 0)

      module top:
        input clk: UInt<1>
        input in_top: UInt<64>
        output out_top: UInt<64>

        wire _auto_firrtl_cc_99_rename_invalid_rhs_references_20: UInt<64>
        wire pass_in_wire: UInt<64>
        wire _3: UInt<64>

        _3 <= _auto_firrtl_cc_99_rename_invalid_rhs_references_20

        inst input_regchain of _paramod_parametric_regchain_NUM_STG_2_WIDTH_64
        input_regchain.clk <= clk
        input_regchain.in <= in_top
        inst passthrough of nonparametric_passthrough
        passthrough.pass_in <= pass_in_wire
        _auto_firrtl_cc_99_rename_invalid_rhs_references_20 <= bits(passthrough.pass_out, 63, 0)
        out_top <= bits(_3, 63, 0)
        pass_in_wire <= bits(input_regchain.out, 63, 0)